# Generated by Django 5.2.12 on 2026-03-11 21:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_diseases', models.TextField(blank=True, null=True)),
                ('low_calories_kcal', models.FloatField(blank=True, null=True)),
                ('high_calories_kcal', models.FloatField(blank=True, null=True)),
                ('low_saturated_fat_g', models.FloatField(blank=True, null=True)),
                ('high_saturated_fat_g', models.FloatField(blank=True, null=True)),
                ('low_carbs_g', models.FloatField(blank=True, null=True)),
                ('high_carbs_g', models.FloatField(blank=True, null=True)),
                ('low_protein_g', models.FloatField(blank=True, null=True)),
                ('high_protein_g', models.FloatField(blank=True, null=True)),
                ('low_fiber_g', models.FloatField(blank=True, null=True)),
                ('high_fiber_g', models.FloatField(blank=True, null=True)),
                ('low_sugar_g', models.FloatField(blank=True, null=True)),
                ('high_sugar_g', models.FloatField(blank=True, null=True)),
                ('low_cholesterol_mg', models.FloatField(blank=True, null=True)),
                ('high_cholesterol_mg', models.FloatField(blank=True, null=True)),
                ('low_sodium_mg', models.FloatField(blank=True, null=True)),
                ('high_sodium_mg', models.FloatField(blank=True, null=True)),
                ('low_potassium_mg', models.FloatField(blank=True, null=True)),
                ('high_potassium_mg', models.FloatField(blank=True, null=True)),
                ('low_iron_mg', models.FloatField(blank=True, null=True)),
                ('high_iron_mg', models.FloatField(blank=True, null=True)),
                ('low_calcium_mg', models.FloatField(blank=True, null=True)),
                ('high_calcium_mg', models.FloatField(blank=True, null=True)),
                ('low_phosphorus_mg', models.FloatField(blank=True, null=True)),
                ('high_phosphorus_mg', models.FloatField(blank=True, null=True)),
                ('low_magnesium_mg', models.FloatField(blank=True, null=True)),
                ('high_magnesium_mg', models.FloatField(blank=True, null=True)),
                ('low_vitamin_a_ug', models.FloatField(blank=True, null=True)),
                ('high_vitamin_a_ug', models.FloatField(blank=True, null=True)),
                ('low_vitamin_b_mg', models.FloatField(blank=True, null=True)),
                ('high_vitamin_b_mg', models.FloatField(blank=True, null=True)),
                ('low_vitamin_c_mg', models.FloatField(blank=True, null=True)),
                ('high_vitamin_c_mg', models.FloatField(blank=True, null=True)),
                ('low_vitamin_d_ug', models.FloatField(blank=True, null=True)),
                ('high_vitamin_d_ug', models.FloatField(blank=True, null=True)),
                ('low_vitamin_e_mg', models.FloatField(blank=True, null=True)),
                ('high_vitamin_e_mg', models.FloatField(blank=True, null=True)),
                ('low_vitamin_k_ug', models.FloatField(blank=True, null=True)),
                ('high_vitamin_k_ug', models.FloatField(blank=True, null=True)),
                ('low_zinc_mg', models.FloatField(blank=True, null=True)),
                ('high_zinc_mg', models.FloatField(blank=True, null=True)),
                ('low_iodine_ug', models.FloatField(blank=True, null=True)),
                ('high_iodine_ug', models.FloatField(blank=True, null=True)),
                ('low_selenium_ug', models.FloatField(blank=True, null=True)),
                ('high_selenium_ug', models.FloatField(blank=True, null=True)),
                ('low_copper_mg', models.FloatField(blank=True, null=True)),
                ('high_copper_mg', models.FloatField(blank=True, null=True)),
                ('low_fluoride_mg', models.FloatField(blank=True, null=True)),
                ('high_fluoride_mg', models.FloatField(blank=True, null=True)),
                ('low_chromium_mg', models.FloatField(blank=True, null=True)),
                ('high_chromium_mg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('measurements', models.TextField(blank=True, null=True)),
                ('measurement_amount', models.FloatField(blank=True, null=True)),
                ('calories_kcal', models.FloatField(blank=True, null=True)),
                ('saturated_fat_g', models.FloatField(blank=True, null=True)),
                ('carbs_g', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('sugar_g', models.FloatField(blank=True, null=True)),
                ('cholesterol_mg', models.FloatField(blank=True, null=True)),
                ('sodium_mg', models.FloatField(blank=True, null=True)),
                ('potassium_mg', models.FloatField(blank=True, null=True)),
                ('iron_mg', models.FloatField(blank=True, null=True)),
                ('calcium_mg', models.FloatField(blank=True, null=True)),
                ('phosphorus_mg', models.FloatField(blank=True, null=True)),
                ('magnesium_mg', models.FloatField(blank=True, null=True)),
                ('vitamin_a_ug', models.FloatField(blank=True, null=True)),
                ('vitamin_b_mg', models.FloatField(blank=True, null=True)),
                ('vitamin_c_mg', models.FloatField(blank=True, null=True)),
                ('vitamin_d_ug', models.FloatField(blank=True, null=True)),
                ('vitamin_e_mg', models.FloatField(blank=True, null=True)),
                ('vitamin_k_ug', models.FloatField(blank=True, null=True)),
                ('zinc_mg', models.FloatField(blank=True, null=True)),
                ('iodine_ug', models.FloatField(blank=True, null=True)),
                ('selenium_ug', models.FloatField(blank=True, null=True)),
                ('copper_mg', models.FloatField(blank=True, null=True)),
                ('fluoride_mg', models.FloatField(blank=True, null=True)),
                ('chromium_mg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('meal_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients', models.TextField(blank=True)),
                ('how_to_cook', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fats', models.FloatField(default=0)),
                ('total_burned', models.FloatField(default=0)),
                ('calorie_goal', models.FloatField(default=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('dietary_restriction', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('goal_weight', models.FloatField(blank=True, null=True)),
                ('allergy', models.CharField(blank=True, max_length=255, null=True)),
                ('meals_per', models.IntegerField(blank=True, null=True)),
                ('snacks_per', models.IntegerField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diseases', models.ManyToManyField(blank=True, to='recipes.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('time_period', models.CharField(blank=True, max_length=20, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(default='Meal', max_length=200)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='recipes.dailylog')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPickedDisease',
            fields=[
                ('disease', models.TextField(blank=True, null=True)),
                ('disease_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserPickedRecipes',
            fields=[
                ('recipe', models.TextField(blank=True, null=True)),
                ('disease_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to='recipes.appuser')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('yoga', 'Yoga'), ('sports', 'Sports'), ('walking', 'Walking'), ('running', 'Running'), ('other', 'Other')], max_length=50)),
                ('calories_burned', models.FloatField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='recipes.dailylog')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Disease_Super_Food',
            fields=[
                ('disease_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.disease')),
                ('ingredient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('disease_id', 'ingredient_id'), name='uniq_disease_superfood')],
            },
        ),
        migrations.CreateModel(
            name='Disease_Avoid_Food',
            fields=[
                ('disease_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.disease')),
                ('ingredient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('disease_id', 'ingredient_id'), name='uniq_disease_avoidfood')],
            },
        ),
        migrations.CreateModel(
            name='Recipe_Ingredients',
            fields=[
                ('amount', models.FloatField(blank=True, null=True)),
                ('recipe_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe_id', 'ingredient_id'), name='uniq_recipe_ingredient')],
            },
        ),
    ]
