# Generated by Django 5.2.12 on 2026-03-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='calorie_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='carb_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='fat_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='protein_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='weight_goal_type',
            field=models.CharField(blank=True, choices=[('lose', 'Lose Weight'), ('gain', 'Gain Weight'), ('maintain', 'Maintain Weight')], max_length=20, null=True),
        ),
    ]
