# Generated by Django 5.2.11 on 2026-03-12 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_dietaryrestriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryrestriction',
            name='name',
        ),
        migrations.AddField(
            model_name='dietaryrestriction',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietaryrestriction',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Dietary_Restriction_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restriction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.dietaryrestriction')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Dietary_Restriction_Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restriction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.dietaryrestriction')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
