# Generated by Django 5.2.11 on 2026-03-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_dietaryrestriction_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serving',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
