# Generated by Django 5.2.11 on 2026-03-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpickedrecipes',
            name='servings_requested',
            field=models.IntegerField(default=1),
        ),
    ]
